### ISSUE TITLE
关于窗口排列功能加强的建议

### ISSUE THREAD

**Issue by maolion** [makeflow/biu#11]
biu的窗口排列 会在每次打开相同一组 process 时窗口会使用最近的排列的方式来显示到布局上

----

![52a9e05bcb9fad488d2fcc86defbd13f](https://user-images.githubusercontent.com/1732779/47158583-91005d80-d31e-11e8-9f2f-b748d1c67cbe.jpg)

**Comment by dizys** [comment]
那个 同一组是指那个 GROUP 哇？什么时机保存布局比较好勒~~~

**Comment by dizys** [comment]
https://github.com/makeflow/biu/commit/7912bfe91b9acbe3519f607c4ac2e8e4732a0bcb
@maolion 
现在 手动移动布局会保存到 localStorage 
然后 工具栏新添了一个按钮 可以一键恢复上次保存的对应布局
狮子 看看这样可以挖？~~
